import "./globals.css";
import { Instrument_Sans } from "next/font/google";

const instrument = Instrument_Sans({
  variable: "--font-instrument",
  subsets: ["latin"],
  preload: true,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${instrument.variable} min-h-screen bg-gray-50 font-sans text-base font-normal text-gray-900 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
